# Generated by Django 5.1.7 on 2025-03-18 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, help_text='Utilize o formato (XX) XXXX-XXXX', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido. Utilize o formato (XX) XXXX-XXXX', regex='^\\(?d{2}\\)?\\s?\\d{4,5}-?\\d{4}')])),
                ('codename', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('V', 'Vingadores'), ('L', 'Liga da Justiça')], default='L', help_text='Escolha um grupo', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
